name: CD-Run Workflow
on:
  workflow_run:
    workflows:
      - cd
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Connecting to AliCloud and run latest image.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_PRIVATE_KEY }}
          script: |
            docker rm -f taccisum-online
            docker run \
            -p 8080:8080 \
            -d \
            --name taccisum-online \
            taccisum/taccisum-online
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Do nothing beacuse of "CD Workflow" is failure.'
