name: CD Workflow
on:
  push:
    tags:
      - v*

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        id: get_version
        run: |
          echo "::set-output name=VERSION::$(echo 'refs/tags/v0.1.7' | sed 's/refs\/tags\/v//')"
      - run: echo ${{ steps.get_version.outputs.VERSION }}

      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Docker
        run: docker --version

      - name: Build Jar Package
        run: mvn clean package

      - run: ls -la ./target

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taccisum-online:${{ steps.get_version.outputs.VERSION }}
